version: 1.0
stages:
  - clone
  - build
  - test

steps:
  clone_step:
    title: Cloning repository
    type: git-clone
    repo: philzona/simple-java-maven-app
    revision: '${{CF_BRANCH}}'
    git: github-pzona
    stage: clone
  build_step:
    title: Build step
    type: build
    description: Build my image
    stage: build
    working_directory: '${{clone_step}}'
    registry: codefreshphil
    arguments:
      image_name: codefreshphil/simple-java-maven-app
      tags: 
        - '${{CF_REVISION}}'
        - latest
  test_step:
    title: Test step
    type: freestyle
    description: Running a test
    stage: test
    image: ${{build_step}}
    commands:
      - pwd